version: '3.6'

services:

  vault_s1:
    build:
      context: ./vault_s1
      dockerfile: Dockerfile
    ports:
      - 8200:8200
    volumes:
      - ./vault_s1/config:/vault/config
      - ./vault_s1/policies:/vault/policies
      - ./vault_s1/data:/vault/data
      - ./vault_s1/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.1.42.201

  consul_c1:
    build:
      context: ./consul_c1
      dockerfile: Dockerfile
    ports:
      - 8503:8500
    command: agent -config-file=/consul/config/config.json
    volumes:
      - ./consul_c1/config/consul-config.json:/consul/config/config.json
      - ./consul_c1/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.10

  vault_s2:
    build:
      context: ./vault_s2
      dockerfile: Dockerfile
    ports:
      - 8205:8200
    volumes:
      - ./vault_s2/config:/vault/config
      - ./vault_s2/policies:/vault/policies
      - ./vault_s2/data:/vault/data
      - ./vault_s2/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.1.42.202

  consul_c2:
    build:
      context: ./consul_c2
      dockerfile: Dockerfile
    ports:
      - 8504:8500
    command: agent -config-file=/consul/config/config.json
    volumes:
      - ./consul_c2/config/consul-config.json:/consul/config/config.json
      - ./consul_c2/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.11

  vault_s3:
    build:
      context: ./vault_s3
      dockerfile: Dockerfile
    ports:
      - 8202:8200
    volumes:
      - ./vault_s3/config:/vault/config
      - ./vault_s3/policies:/vault/policies
      - ./vault_s3/data:/vault/data
      - ./vault_s3/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      vpcbr:
        ipv4_address: 10.1.42.203

  consul_c3:
    build:
      context: ./consul_c3
      dockerfile: Dockerfile
    ports:
      - 8505:8500
    command: agent -config-file=/consul/config/config.json
    volumes:
      - ./consul_c3/config/consul-config.json:/consul/config/config.json
      - ./consul_c3/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.12

  consul_s1:
    build:
      context: ./consul_s1
      dockerfile: Dockerfile
    ports:
      - 8500:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s1/config/consul-config.json:/consul/config/config.json
      - ./consul_s1/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.101

  consul_s2:
    build:
      context: ./consul_s2
      dockerfile: Dockerfile
    ports:
      - 8501:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s2/config/consul-config.json:/consul/config/config.json
      - ./consul_s2/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.102

  consul_s3:
    build:
      context: ./consul_s3
      dockerfile: Dockerfile
    ports:
      - 8502:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s3/config/consul-config.json:/consul/config/config.json
      - ./consul_s3/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.103

  consul_s4:
    build:
      context: ./consul_s4
      dockerfile: Dockerfile
    ports:
      - 8510:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s4/config/consul-config.json:/consul/config/config.json
      - ./consul_s4/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.104

  consul_s5:
    build:
      context: ./consul_s5
      dockerfile: Dockerfile
    ports:
      - 8511:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s5/config/consul-config.json:/consul/config/config.json
      - ./consul_s5/data:/consul/data
    networks:
      vpcbr:
        ipv4_address: 10.1.42.105

  haproxy_s1:
    build:
      context: ./haproxy_s1
      dockerfile: Dockerfile
    volumes:
      - ./haproxy_s1/src:/usr/local/etc/haproxy
    ports:
    - "8080:8200"
    environment:
      # DNS_ENABLED: "true"
      LOG_LEVEL: "debug"
    networks:
      vpcbr:
        ipv4_address: 10.1.42.20

networks:
  vpcbr:
    driver: bridge
    ipam:
     config:
       - subnet: 10.1.42.0/24
         gateway: 10.1.42.1