version: '3.6'

services:

  vault_s2:
    build:
      context: ./vault_s2
      dockerfile: Dockerfile
    ports:
      - 8205:8200
    volumes:
      - ./vault_s2/config:/vault/config
      - ./vault_s2/policies:/vault/policies
      - ./vault_s2/data:/vault/data
      - ./vault_s2/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      vault_network:
        ipv4_address: 10.1.42.202

  consul_c2:
    build:
      context: ./consul_c2
      dockerfile: Dockerfile
    ports:
      - 8504:8500
    command: agent -config-file=/consul/config/config.json
    volumes:
      - ./consul_c2/config/consul-config.json:/consul/config/config.json
      - ./consul_c2/data:/consul/data
    networks:
      vault_network:
        ipv4_address: 10.1.42.11

  consul_s2:
    build:
      context: ./consul_s2
      dockerfile: Dockerfile
    ports:
      - 8501:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s2/config/consul-config.json:/consul/config/config.json
      - ./consul_s2/data:/consul/data
    networks:
      vault_network:
        ipv4_address: 10.1.42.102

networks:
  vault_network:
    external: true
