version: '3.6'

services:

  vault_s3:
    build:
      context: ./vault_s3
      dockerfile: Dockerfile
    ports:
      - 8202:8200
    volumes:
      - ./vault_s3/config:/vault/config
      - ./vault_s3/policies:/vault/policies
      - ./vault_s3/data:/vault/data
      - ./vault_s3/logs:/vault/logs
    environment:
      - VAULT_ADDR=http://127.0.0.1:8200
    command: server -config=/vault/config/vault-config.hcl
    cap_add:
      - IPC_LOCK
    networks:
      vault_network:
        ipv4_address: 10.1.42.203

  consul_c3:
    build:
      context: ./consul_c3
      dockerfile: Dockerfile
    ports:
      - 8505:8500
    command: agent -config-file=/consul/config/config.json
    volumes:
      - ./consul_c3/config/consul-config.json:/consul/config/config.json
      - ./consul_c3/data:/consul/data
    networks:
      vault_network:
        ipv4_address: 10.1.42.12

  consul_s3:
    build:
      context: ./consul_s3
      dockerfile: Dockerfile
    ports:
      - 8502:8500
    command: agent -server -bind 0.0.0.0 -client 0.0.0.0 -bootstrap-expect 3 -config-file=/consul/config/config.json
    volumes:
      - ./consul_s3/config/consul-config.json:/consul/config/config.json
      - ./consul_s3/data:/consul/data
    networks:
      vault_network:
        ipv4_address: 10.1.42.103

networks:
  vault_network:
    external: true
